apiVersion: v1
kind: Secret
metadata:
  name: busconnect-secret
  namespace: {{ include "busconnect.namespace" . }}
  labels:
    {{- include "busconnect.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET:  {{ .Values.secrets.jwtSecret | quote }}
  SMTP_USER:   {{ .Values.secrets.smtpUser | quote }}
  SMTP_PASS:   {{ .Values.secrets.smtpPass | quote }}
